Gabriel Khot Garang Pawuoi

diff --git a/python-hello_world/101-compile b/python-hello_world/101-compile
--- a/python-hello_world/101-compile
+++ b/python-hello_world/101-compile
@@ -1,3 +1,21 @@
 #!/bin/bash
-python3 -m compileall $PYFILE -b
-Give feedback
+if [ -z "$PYFILE" ]; then
+    echo "PYFILE environment variable is not set."
+    exit 1
+fi
+# Check if the specified Python file exists
+if [ ! -f "$PYFILE" ]; then
+    echo "Python file $PYFILE does not exist."
+    exit 1
+fi
+# Compile the Python script using the "py_compile" module
+python3 -m py_compile "$PYFILE"
+if [ $? -eq 0 ]; then
+    echo "Compiling $PYFILE ..."
+    compiled_filename="${PYFILE}c"
+    mv "__pycache__/${PYFILE%.py}*.pyc" "$compiled_filename"
+    rm -rf "__pycache__"
+    echo "Compilation successful. Compiled file: $compiled_filename"
+else
+    echo "Compilation failed."
+fi
